### ISSUE TITLE
Add more information about what a TRP server/client is

### ISSUE THREAD

**Issue by EehMauro** [tx3-lang/docs#10]
When starting to follow the quickstart there are not references about what a TRP server/client is
But you need to setup one in order to use cshell and in order to run the generated code

Also there are some settings for the `trix.toml` file that needs to be addressed on the docs:
```toml
[profiles.devnet.network]
rpc_url = "http://localhost:8545/"
chain_id = 1337

[profiles.devnet.trp]
url = "https://cardano-preview.trp-m1.demeter.run/"

[profiles.devnet.trp.headers]
dmtr-api-key = "trpjodqbmjblunzpbikpcrl"
```
